#Docker compose file used for building and running the images contained in this repository.
services:
  mediawiki-sqlite:
    image: ${MEDIAWIKI_SQLITE:-appropedia-mediawiki-sqlite}
    build:
      dockerfile: Dockerfile.mediawiki-sqlite
  local-minimal:
    image: ${LOCAL_MINIMAL:-appropedia-local-minimal}
    build:
      dockerfile: Dockerfile.local-minimal
      additional_contexts:
        mediawiki-sqlite: "service:mediawiki-sqlite"
      args:
        - BACKUP_FILE=current-text.xml.gz
    ports:
      - 80:80
  local-full:
    image: ${LOCAL_FULL:-appropedia-local-full}
    build:
      dockerfile: Dockerfile.local-full
      additional_contexts:
        mediawiki-sqlite: "service:mediawiki-sqlite"
      args:
        - BACKUP_FILE=current-with-files.xml.gz
    ports:
      - 80:80
